---
version: '3.5'
# Start with:
#  SUPEREDITORS=$(id -u) docker-compose -f *-compose.yml -f d*-compose-dev.yml  up -t 0 -d --force-recreate solr
#
x-image: &image_template
  environment:
  - SUPEREDITORS=$SUPEREDITORS
  - DEBUG=1
  - "DOCKER_SKIP_START=${DOCKER_SKIP_START-}"
  - |
    A_RECONFIGURE=---
    only_steps: true
    cops_solr_lifecycle_app_push_code: false
    cops_solr_s_docker_reconfigure: true
    cops_solr_s_layout: true
    cops_solr_s_first_fixperms: true
    cops_solr_s_setup: true
    # cops_solr_has_reverse_proxy: false
    cops_solr_http_users:
    - {user: admin,  password: "password4yZ8e4Ef8K824Sk"}
  - |
    A_POSTCONFIGURE=---
    only_steps: true
    cops_solr_lifecycle_app_push_code: false
    cops_solr_s_manage_content: true
    # cops_solr_has_reverse_proxy: false
  command: >
    sh -c 'if [ "x$DOCKER_SKIP_START" != x ];
    then while true;do echo sleeping;sleep 65535;done
    else exec /app_entry_point;
    fi'
  # for now this is a bloat image-as-a-vm to make a dev env ligther than a vagrant VM
  tmpfs: [/run, /run/lock]
  volumes: &image_volumes
  # systemd
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # data
  - "./local/setup:/setup"
  - "./local/data/solr:/srv/projects/solr/data"
  # sources
  - "./.git:/srv/projects/solrproject/project/.git"
  - "./.gitignore:/srv/projects/solrproject/project/.gitignore"
  - "./.gitmodules:/srv/projects/solrproject/project/.gitmodules"
  # provision
  - "./.ansible/vaults:/provision_dir/.ansible/vaults"
  - "./.ansible/scripts:/provision_dir/.ansible/scripts"
  - "./.ansible/playbooks:/provision_dir/.ansible/playbooks"
  # Need a bind mount in local/corpusops.bootstrap instead of the symlink
  #- "./local/corpusops.bootstrap/bin:/srv/corpusops/corpusops.bootstrap/bin"
  #- "./local/corpusops.bootstrap/hacking:/srv/corpusops/corpusops.bootstrap/hacking"
  #- "./local/corpusops.bootstrap/roles:/srv/corpusops/corpusops.bootstrap/roles"
  #- "./local/corpusops.bootstrap/requirements:/srv/corpusops/corpusops.bootstrap/requirements"
  #- "./local/corpusops.bootstrap/docs:/srv/corpusops/corpusops.bootstrap/docs"
  # Remember: /setup/rootfs/ is synced inside the container /
  #- "./local/app_entry_point:/app_entry_point"
  #- "./local/entry_point:/entry_point"
  #- "./local/reconfigure.sh:/provision_dir/reconfigure.sh"
services:
  solr:
    <<:  [ *image_template ]
