---
- listen: restart_cops_solr
  become: true
  cops_service:
    daemon_reload: yes
    state: restarted
    name: "{{item}}"
  loop: "{{cops_solr_vars.services}}"
  tags: [cops_solr_handlers, cops_solr_handlers_restart]
  when: "(cops_solr_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr == 'systemd'))"
- listen: restart_cops_solr
  become: true
  cops_service:
    state: restarted
    name: "{{item}}"
  loop: "{{cops_solr_vars.services}}"
  tags: [cops_solr_handlers, cops_solr_handlers_restart]
  when: "(cops_solr_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr != 'systemd'))"
- listen: reload_cops_solr
  become: true
  cops_service:
    daemon_reload: yes
    state: reloaded
    name: "{{item}}"
  loop: "{{cops_solr_vars.services}}"
  tags: [cops_solr_handlers, cops_solr_handlers_reload]
  when: "(cops_solr_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr == 'systemd'))"
- listen: reload_cops_solr
  become: true
  cops_service:
    state: reloaded
    name: "{{item}}"
  loop: "{{cops_solr_vars.services}}"
  tags: [cops_solr_handlers, cops_solr_handlers_reload]
  when: "(cops_solr_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr != 'systemd'))"
