---
- include_tasks: lc_push_code.yml
  when: cops_solr_lifecycle_app_push_code|cops_solr_lifecycle_app
  tags: [cops_solr_lifecycle_app_push_code]
- include_tasks: lc_app.yml
  when: cops_solr_lifecycle_app_setup|cops_solr_lifecycle_app
  tags: [cops_solr_lifecycle_app]
