---
# generate password on remote box if not found
- name: "solr secret generation: {{solrsecret}}"
  include_role:
    name: corpusops.roles/get_secret_variable
  vars:
    _cops_get_secret_variable:
      name: "cops_solr_{{solrsecret}}"
      path: "/etc/solr-{{cops_solr_vars.name}}-secrets"
  when: not vars.get('cops_solr_{0}'.format(solrsecret), None)
  no_log: "{{not (cops_secret_vars_debug|default(false))}}"
- debug:
    var: "{{'cops_solr_{0}'.format(solrsecret)}}"
  register: cops_secret_value
  no_log: "{{not (cops_secret_vars_debug|default(false))}}"
- name: "Update registry with {{solrsecret}}"
  include_jinja_vars:
    content: |
      ---
      {% set d = solrsecret %}
      {% set p = 'cops_solr_' %}
      {% set v = p+d %}
      {% set n = p+'vars' %}
      {% set _vars = {} %}
      {% set _ = _vars.update(cops_secret_value) %}
      {{(_vars | copsf_registry(p, namespaced=vars[n]))[0]| to_json }}
  no_log: "{{not (cops_vars_debug|default(false))}}"
